name: vancitybroker.com
favicon: null
layout_spectrum: 0.99727
typography_spectrum: 1
title: 'Vancouver Realtor and Business Broker '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00285b'
    - '#fff0e9'
    - '#006cae'
    - '#b0bfd0'
    - '#6195ba'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5059187482111156
  rhythmicContrast: 0.75
purpose: []
